### PR TITLE
Move lambda arguments to the end to match faunadb-ruby

### PR DESCRIPTION
**Pull request by andy-faunadb**
This is a breaking change, so we might need to tell the client about this / change the version number.

### CODE REVIEW

**Comment by evan** [comment]
Changing the version should be ok; we should minimize breaking changes when practical, but if we are at a pre-1.0 version number pretty much any release is "allowed" to be breaking.

**Comment by eaceaser** [comment]
can we just use semver-style shit?

just start at 0.1.0, and increment the minor for any breaking change, until we finally release 1.0

**Comment by andy-faunadb** [comment]
We're not changing faunadb-python to match faunadb-ruby, but still, I think putting a function at the end is standard for js libraries.

**Comment by eaceaser** [comment]
lgtm

**Pull request merged**
