### PR TITLE
Add coverage to JS CI

### PR DESCRIPTION
**Pull request by ashfire908**
Depends on #97.

### CODE REVIEW

**Comment by erickpintor** [comment]
Are you going to add badges on the readme file?

**Comment by ashfire908** [comment]
Woops, yes, forgot to though. Will fix.

**Comment by erickpintor** [comment]
Why does the travis badge shows as unknown? Is that because we didn't merge #97 yet?

**Comment by ashfire908** [comment]
Yes.

**Comment by erickpintor** [comment]
LGTM

**Comment by eaceaser** [comment]
lgtm

**Pull request merged**
